### ISSUE TITLE
The problems about the imu pose representation using SE2(3) ?

### ISSUE THREAD

**Issue by Freeecode** [MAVIS-SLAM/OpenMAVIS#10]
Thanks for sharing the execllent work!
I have read the paper and the open source code and I have some problems.
This paper proposed SE2(3) based pre-integration and the IMU pose also used the representation , SE2(3) Lie Group, However, when performing optimization, the pose update does not follow the rule of SE2(3) Lie Group, which is same as original ORB-SLAM3. In SE2(3) Lie Group, the velocity is also related to rotation part. In addition, the defination of error terms in EdgeInertial, which  also is same as original ORB-SLAM3.

Looking forward to your reply!
Best wishes！

**Comment by 1fwang** [comment]
> Thanks for sharing the execllent work! I have read the paper and the open source code and I have some probles This paper proposed SE2(3) based pre-integration and the IMU pose also used the representation , SE2(3) Lie Group, However, when performing optimization, the pose update not follow the rule of SE2(3) Lie Group, which is same as original ORB-SLAM3. In SE2(3) Lie Group, the velocity is also related to rotation part. In addition, the defination of error terms in EdgeInertial, which also is same as original ORB-SLAM3.
> 
> Looking forward to your reply! Best wishes！

Thanks for your message!

It seems the backend hasn’t been updated with the new pre-integration formulation yet; it’s currently applied only to the Imutypes.h now. I’ll look into it when I have time (though I’m extremely busy in the next couple of months). Stay tuned.

In the meantime, if you’re able to help implement it, I’d be happy to review and merge a pull request after testing.

**Comment by Freeecode** [comment]
Limitted by my ability, it is hard for me to implement it , but I will try to do it! by the way,  the current implementation have no influences on the  experiments in some degree.

**Comment by 1fwang** [comment]
> Limitted by my ability, it is hard for me to implement it , but I will try to do it! by the way, the current implementation have no influences on the experiments in some degree.

The main purpose of SE2(3) is to provide more precise integrated poses in corner cases, such as fast rotations or visual degradation. On one hand, more accurate pre-integration can slightly improve front-end feature tracking in the local tracking module; on the other hand, it can sustain longer without divergence during visual loss. Indeed, in many carefully selected motions or scenes in SLAM datasets, the impact of SE2(3) is not particularly apparent.

**Comment by Freeecode** [comment]
Thanks for your kind replay! I have tested invaraint EKF, which also based on SE2(3). In some corner cases, the invariant ekf can run longer without divergence, and the performance of the invariant ekf is corresponded to the eskf in most cases.

**Comment by 1fwang** [comment]
> Thanks for your kind replay! I have tested invaraint EKF, which also based on SE2(3). In some corner cases, the invariant ekf can run longer without divergence, and the performance of the invariant ekf is corresponded to the eskf in most cases.

Exactly, I think you are mentioning this: https://github.com/aau-cns/equivariant-preintegration.

**Comment by Freeecode** [comment]
> Exactly, I think you are mentioning this: https://github.com/aau-cns/equivariant-preintegration.

Wow, I will try this code later ！Thanks again！

**Comment by 1fwang** [comment]
> > Exactly, I think you are mentioning this: https://github.com/aau-cns/equivariant-preintegration.
> 
> Wow, I will try this code later ！Thanks again！
