### ISSUE TITLE
Can streo in mutil be replaced with an rgbd camera?

### ISSUE THREAD

**Issue by jieli1990** [MAVIS-SLAM/OpenMAVIS#5]
I want to replace streo in mutil with rgbd camera. Can I just replace the corresponding code?

**Comment by 1fwang** [comment]
> I want to replace streo in mutil with rgbd camera. Can I just replace the corresponding code?

Hi, 

Yes you can change stereo camera with rgbd, but I requires some modification acrossing the entire project I believe. You can imagine this version is more like an extension of stereo-fisheye-inertial pipeline with additional 2 sideward mono-camera. 

BR

**Comment by jieli1990** [comment]
thanks
