### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by langsung01** [MAVIS-SLAM/OpenMAVIS#6]
Your work is impressive!
But has anyone successfully run OpenMAVIS?
I'm facing an error, and I think it might be related to the source code.
 
 ubuntu 20.04 
 opencv 4.4.0
 
 home/OpenMAVIS/src/Optimizer.cc:3881:11: warning: unused variable 'err_end' [-Wunused-variable]
 3881 |     float err_end = optimizer.activeRobustChi2();
      |           ^~~~~~~
/home/OpenMAVIS/src/Optimizer.cc: In static member function 'static void ORB_SLAM3::Optimizer::LocalBundleAdjustment(ORB_SLAM3::KeyFrame*, std::vector<ORB_SLAM3::KeyFrame*>, std::vector<ORB_SLAM3::KeyFrame*>, bool*)':
/home/OpenMAVIS/src/Optimizer.cc:3889:10: warning: unused variable 'bShowImages' [-Wunused-variable]
 3889 |     bool bShowImages = false;
      |          ^~~~~~~~~~~
/home/OpenMAVIS/src/Optimizer.cc: In static member function 'static void ORB_SLAM3::Optimizer::MergeInertialBA(ORB_SLAM3::KeyFrame*, ORB_SLAM3::KeyFrame*, bool*, ORB_SLAM3::Map*, ORB_SLAM3::LoopClosing::KeyFrameAndPose&)':
/home/OpenMAVIS/src/Optimizer.cc:4424:19: warning: suggest explicit braces to avoid ambiguous 'else' [-Wdangling-else]
 4424 |                 if(!pMP->isBad())
      |                   ^
/home/OpenMAVIS/src/Optimizer.cc:4745:25: warning: unused variable 'rightIndex' [-Wunused-variable]
 4745 |                     int rightIndex = get<1>(mit->second);
      |                         ^~~~~~~~~~
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:216: CMakeFiles/ORB_SLAM3.dir/src/Atlas.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:244: CMakeFiles/ORB_SLAM3.dir/src/MapDrawer.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:286: CMakeFiles/ORB_SLAM3.dir/src/KeyFrameDatabase.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:314: CMakeFiles/ORB_SLAM3.dir/src/Viewer.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:412: CMakeFiles/ORB_SLAM3.dir/src/GeometricTools.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:160: CMakeFiles/ORB_SLAM3.dir/src/FrameDrawer.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:230: CMakeFiles/ORB_SLAM3.dir/src/Map.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:146: CMakeFiles/ORB_SLAM3.dir/src/ORBmatcher.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:188: CMakeFiles/ORB_SLAM3.dir/src/MapPoint.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:202: CMakeFiles/ORB_SLAM3.dir/src/KeyFrame.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:454: CMakeFiles/ORB_SLAM3.dir/src/Settings.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:76: CMakeFiles/ORB_SLAM3.dir/src/System.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:104: CMakeFiles/ORB_SLAM3.dir/src/LocalMapping.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:300: CMakeFiles/ORB_SLAM3.dir/src/Sim3Solver.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:398: CMakeFiles/ORB_SLAM3.dir/src/MLPnPsolver.cpp.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:272: CMakeFiles/ORB_SLAM3.dir/src/Frame.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:90: CMakeFiles/ORB_SLAM3.dir/src/Tracking.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:118: CMakeFiles/ORB_SLAM3.dir/src/LoopClosing.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:342: CMakeFiles/ORB_SLAM3.dir/src/G2oTypes.cc.o] Error 1
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:258: CMakeFiles/ORB_SLAM3.dir/src/Optimizer.cc.o] Error 1
make[2]: Leaving directory '/home/OpenMAVIS/build'
make[1]: *** [CMakeFiles/Makefile2:150: CMakeFiles/ORB_SLAM3.dir/all] Error 2
make[1]: Leaving directory '/home/OpenMAVIS/build'
make: *** [Makefile:91: all] Error 2

**Comment by 1fwang** [comment]
Hi, have you successfully built ORB-SLAM3 before? I recommend following the ORB-SLAM3 tutorial for setup; the process should be the same.

> Your work is impressive! But has anyone successfully run OpenMAVIS? I'm facing an error, and I think it might be related to the source code.
> 
> ubuntu 20.04 opencv 4.4.0
> 
> home/OpenMAVIS/src/Optimizer.cc:3881:11: warning: unused variable 'err_end' [-Wunused-variable] 3881 | float err_end = optimizer.activeRobustChi2(); | ^~~~~~~ /home/OpenMAVIS/src/Optimizer.cc: In static member function 'static void ORB_SLAM3::Optimizer::LocalBundleAdjustment(ORB_SLAM3::KeyFrame*, std::vector<ORB_SLAM3::KeyFrame*>, std::vector<ORB_SLAM3::KeyFrame*>, bool*)': /home/OpenMAVIS/src/Optimizer.cc:3889:10: warning: unused variable 'bShowImages' [-Wunused-variable] 3889 | bool bShowImages = false; | ^~~~~~~~~~~ /home/OpenMAVIS/src/Optimizer.cc: In static member function 'static void ORB_SLAM3::Optimizer::MergeInertialBA(ORB_SLAM3::KeyFrame*, ORB_SLAM3::KeyFrame*, bool*, ORB_SLAM3::Map*, ORB_SLAM3::LoopClosing::KeyFrameAndPose&)': /home/OpenMAVIS/src/Optimizer.cc:4424:19: warning: suggest explicit braces to avoid ambiguous 'else' [-Wdangling-else] 4424 | if(!pMP->isBad()) | ^ /home/OpenMAVIS/src/Optimizer.cc:4745:25: warning: unused variable 'rightIndex' [-Wunused-variable] 4745 | int rightIndex = get<1>(mit->second); | ^~~~~~~~~~ make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:216: CMakeFiles/ORB_SLAM3.dir/src/Atlas.cc.o] Error 1 make[2]: *** Waiting for unfinished jobs.... make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:244: CMakeFiles/ORB_SLAM3.dir/src/MapDrawer.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:286: CMakeFiles/ORB_SLAM3.dir/src/KeyFrameDatabase.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:314: CMakeFiles/ORB_SLAM3.dir/src/Viewer.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:412: CMakeFiles/ORB_SLAM3.dir/src/GeometricTools.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:160: CMakeFiles/ORB_SLAM3.dir/src/FrameDrawer.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:230: CMakeFiles/ORB_SLAM3.dir/src/Map.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:146: CMakeFiles/ORB_SLAM3.dir/src/ORBmatcher.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:188: CMakeFiles/ORB_SLAM3.dir/src/MapPoint.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:202: CMakeFiles/ORB_SLAM3.dir/src/KeyFrame.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:454: CMakeFiles/ORB_SLAM3.dir/src/Settings.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:76: CMakeFiles/ORB_SLAM3.dir/src/System.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:104: CMakeFiles/ORB_SLAM3.dir/src/LocalMapping.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:300: CMakeFiles/ORB_SLAM3.dir/src/Sim3Solver.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:398: CMakeFiles/ORB_SLAM3.dir/src/MLPnPsolver.cpp.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:272: CMakeFiles/ORB_SLAM3.dir/src/Frame.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:90: CMakeFiles/ORB_SLAM3.dir/src/Tracking.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:118: CMakeFiles/ORB_SLAM3.dir/src/LoopClosing.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:342: CMakeFiles/ORB_SLAM3.dir/src/G2oTypes.cc.o] Error 1 make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:258: CMakeFiles/ORB_SLAM3.dir/src/Optimizer.cc.o] Error 1 make[2]: Leaving directory '/home/OpenMAVIS/build' make[1]: *** [CMakeFiles/Makefile2:150: CMakeFiles/ORB_SLAM3.dir/all] Error 2 make[1]: Leaving directory '/home/OpenMAVIS/build' make: *** [Makefile:91: all] Error 2

**Comment by langsung01** [comment]
Yes, I did succeed!
 Were you able to build it successfully with the code now?
Is the video in the README a scene rendered with OpenMavis?

**Comment by 1fwang** [comment]
> Yes, I did succeed! Were you able to build it successfully with the code now? Is the video in the README a scene rendered with OpenMavis?

Yes thats the video I recorded last month via OpenMAVIS.

**Comment by langsung01** [comment]
Sounds great! I’m building it in Docker right now, and I’ll give it another try. Have you ever encountered the error I sent above?

**Comment by 1fwang** [comment]
> Sounds great! I’m building it in Docker right now, and I’ll give it another try. Have you ever encountered the error I sent above?

sorry but I'm also using Ubuntu 20.04 and OpenCV4 and haven't encountered these issues.

**Comment by 1fwang** [comment]
> Sounds great! I’m building it in Docker right now, and I’ll give it another try. Have you ever encountered the error I sent above?

hi, have you already solved the issue?

**Comment by langsung01** [comment]
Yes I solved it thank you!
